SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE ORDER_ITEMS;
TRUNCATE TABLE ORDERS;
TRUNCATE TABLE USERS_COUPON;
TRUNCATE TABLE POINT_HISTORY;
TRUNCATE TABLE PRODUCTS;
TRUNCATE TABLE COUPON;
TRUNCATE TABLE USERS;
SET FOREIGN_KEY_CHECKS = 1;
